
// This file has been generated by the GUI designer. Do not modify.
namespace Bizingo
{
	public partial class BizingoTabuleiro
	{
		private global::Gtk.Fixed fixed4;

		private global::Gtk.DrawingArea daTabuleiro;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Bizingo.BizingoTabuleiro
			this.WidthRequest = 800;
			this.HeightRequest = 500;
			this.Name = "Bizingo.BizingoTabuleiro";
			this.Title = global::Mono.Unix.Catalog.GetString("BizingoTabuleiro");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Bizingo.BizingoTabuleiro.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.daTabuleiro = new global::Gtk.DrawingArea();
			this.daTabuleiro.WidthRequest = 440;
			this.daTabuleiro.HeightRequest = 450;
			this.daTabuleiro.Events = ((global::Gdk.EventMask)(256));
			this.daTabuleiro.Name = "daTabuleiro";
			this.fixed4.Add(this.daTabuleiro);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.daTabuleiro]));
			w1.X = 10;
			w1.Y = 10;
			this.Add(this.fixed4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 500;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.daTabuleiro.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnTabuleiroExposeEvent);
			this.daTabuleiro.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnDaTabuleiroButtonPressEvent);
		}
	}
}
