
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.DrawingArea picGameBoard;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("SnakeGame");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.picGameBoard = new global::Gtk.DrawingArea();
		this.picGameBoard.WidthRequest = 420;
		this.picGameBoard.HeightRequest = 420;
		this.picGameBoard.Name = "picGameBoard";
		this.fixed1.Add(this.picGameBoard);
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 420;
		this.DefaultHeight = 420;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnKeyPressed);
		this.picGameBoard.ExposeEvent += new global::Gtk.ExposeEventHandler(this.OnExpose);
	}
}
