
// This file has been generated by the GUI designer. Do not modify.
namespace Chat
{
	public partial class TelaConectar
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Entry ePortaRemota;

		private global::Gtk.Entry eIpRemoto;

		private global::Gtk.Entry ePortaLocal;

		private global::Gtk.Label lbPortaLocal;

		private global::Gtk.Label lbPortaRemota;

		private global::Gtk.Label lbIpRemoto;

		private global::Gtk.Button btCancelar;

		private global::Gtk.Button btOk;

		private global::Gtk.Label label1;

		private global::Gtk.Entry eIpLocal;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Chat.TelaConectar
			this.Name = "Chat.TelaConectar";
			this.Title = global::Mono.Unix.Catalog.GetString("TelaConectar");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child Chat.TelaConectar.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.ePortaRemota = new global::Gtk.Entry();
			this.ePortaRemota.CanFocus = true;
			this.ePortaRemota.Name = "ePortaRemota";
			this.ePortaRemota.IsEditable = true;
			this.ePortaRemota.InvisibleChar = '•';
			this.fixed1.Add(this.ePortaRemota);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ePortaRemota]));
			w1.X = 152;
			w1.Y = 56;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eIpRemoto = new global::Gtk.Entry();
			this.eIpRemoto.CanFocus = true;
			this.eIpRemoto.Name = "eIpRemoto";
			this.eIpRemoto.IsEditable = true;
			this.eIpRemoto.InvisibleChar = '•';
			this.fixed1.Add(this.eIpRemoto);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.eIpRemoto]));
			w2.X = 152;
			w2.Y = 88;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.ePortaLocal = new global::Gtk.Entry();
			this.ePortaLocal.CanFocus = true;
			this.ePortaLocal.Name = "ePortaLocal";
			this.ePortaLocal.IsEditable = true;
			this.ePortaLocal.InvisibleChar = '•';
			this.fixed1.Add(this.ePortaLocal);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.ePortaLocal]));
			w3.X = 152;
			w3.Y = 23;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbPortaLocal = new global::Gtk.Label();
			this.lbPortaLocal.Name = "lbPortaLocal";
			this.lbPortaLocal.LabelProp = global::Mono.Unix.Catalog.GetString("Porta local:");
			this.fixed1.Add(this.lbPortaLocal);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbPortaLocal]));
			w4.X = 69;
			w4.Y = 29;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbPortaRemota = new global::Gtk.Label();
			this.lbPortaRemota.Name = "lbPortaRemota";
			this.lbPortaRemota.LabelProp = global::Mono.Unix.Catalog.GetString("Porta Remota:");
			this.fixed1.Add(this.lbPortaRemota);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbPortaRemota]));
			w5.X = 48;
			w5.Y = 59;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbIpRemoto = new global::Gtk.Label();
			this.lbIpRemoto.Name = "lbIpRemoto";
			this.lbIpRemoto.LabelProp = global::Mono.Unix.Catalog.GetString("IP remoto:");
			this.fixed1.Add(this.lbIpRemoto);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbIpRemoto]));
			w6.X = 74;
			w6.Y = 91;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btCancelar = new global::Gtk.Button();
			this.btCancelar.WidthRequest = 90;
			this.btCancelar.CanFocus = true;
			this.btCancelar.Name = "btCancelar";
			this.btCancelar.UseUnderline = true;
			this.btCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btCancelar);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btCancelar]));
			w7.X = 85;
			w7.Y = 153;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btOk = new global::Gtk.Button();
			this.btOk.WidthRequest = 90;
			this.btOk.CanFocus = true;
			this.btOk.Name = "btOk";
			this.btOk.UseUnderline = true;
			this.btOk.Label = global::Mono.Unix.Catalog.GetString("Ok");
			this.fixed1.Add(this.btOk);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btOk]));
			w8.X = 254;
			w8.Y = 153;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("IP local:");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w9.X = 90;
			w9.Y = 124;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eIpLocal = new global::Gtk.Entry();
			this.eIpLocal.CanFocus = true;
			this.eIpLocal.Name = "eIpLocal";
			this.eIpLocal.IsEditable = false;
			this.eIpLocal.InvisibleChar = '•';
			this.fixed1.Add(this.eIpLocal);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.eIpLocal]));
			w10.X = 152;
			w10.Y = 120;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 395;
			this.DefaultHeight = 227;
			this.Show();
			this.btCancelar.Clicked += new global::System.EventHandler(this.OnCancelar);
			this.btOk.Clicked += new global::System.EventHandler(this.OnOkClicked);
		}
	}
}
