
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView tvMensagemEnviar;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView tvMensagemReceber;

	private global::Gtk.Button btEnviar;

	private global::Gtk.Button btConnect;

	private global::Gtk.Button btTestCon;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvMensagemEnviar = new global::Gtk.TextView();
		this.tvMensagemEnviar.WidthRequest = 322;
		this.tvMensagemEnviar.HeightRequest = 67;
		this.tvMensagemEnviar.CanFocus = true;
		this.tvMensagemEnviar.Name = "tvMensagemEnviar";
		this.GtkScrolledWindow.Add(this.tvMensagemEnviar);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w2.X = 6;
		w2.Y = 217;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.tvMensagemReceber = new global::Gtk.TextView();
		this.tvMensagemReceber.WidthRequest = 405;
		this.tvMensagemReceber.HeightRequest = 194;
		this.tvMensagemReceber.CanFocus = true;
		this.tvMensagemReceber.Name = "tvMensagemReceber";
		this.tvMensagemReceber.Editable = false;
		this.GtkScrolledWindow1.Add(this.tvMensagemReceber);
		this.fixed1.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
		w4.X = 10;
		w4.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btEnviar = new global::Gtk.Button();
		this.btEnviar.WidthRequest = 52;
		this.btEnviar.CanFocus = true;
		this.btEnviar.Name = "btEnviar";
		this.btEnviar.UseUnderline = true;
		this.btEnviar.Label = global::Mono.Unix.Catalog.GetString("Enviar");
		this.fixed1.Add(this.btEnviar);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btEnviar]));
		w5.X = 348;
		w5.Y = 263;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btConnect = new global::Gtk.Button();
		this.btConnect.CanFocus = true;
		this.btConnect.Name = "btConnect";
		this.btConnect.UseUnderline = true;
		this.btConnect.Label = global::Mono.Unix.Catalog.GetString("Conectar");
		this.fixed1.Add(this.btConnect);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btConnect]));
		w6.X = 349;
		w6.Y = 224;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btTestCon = new global::Gtk.Button();
		this.btTestCon.CanFocus = true;
		this.btTestCon.Name = "btTestCon";
		this.btTestCon.UseUnderline = true;
		this.btTestCon.Label = global::Mono.Unix.Catalog.GetString("TestCon");
		this.fixed1.Add(this.btTestCon);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btTestCon]));
		w7.X = 428;
		w7.Y = 250;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 530;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btEnviar.Clicked += new global::System.EventHandler(this.OnSendMessage);
		this.btConnect.Clicked += new global::System.EventHandler(this.OnConectar);
		this.btTestCon.Clicked += new global::System.EventHandler(this.OnTestCon);
	}
}
