
// This file has been generated by the GUI designer. Do not modify.
namespace Bizingo
{
	public partial class CriarJogoWindow
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Entry eIpLocal;

		private global::Gtk.Entry ePortaLocal;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Button btnCancelar;

		private global::Gtk.Button btnCriar;

		private global::Gtk.Label label3;

		private global::Gtk.Entry eApelido;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Bizingo.CriarJogoWindow
			this.Name = "Bizingo.CriarJogoWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("CriarJogoWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Bizingo.CriarJogoWindow.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.eIpLocal = new global::Gtk.Entry();
			this.eIpLocal.CanFocus = true;
			this.eIpLocal.Name = "eIpLocal";
			this.eIpLocal.IsEditable = true;
			this.eIpLocal.InvisibleChar = '•';
			this.fixed3.Add(this.eIpLocal);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.eIpLocal]));
			w1.X = 165;
			w1.Y = 59;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.ePortaLocal = new global::Gtk.Entry();
			this.ePortaLocal.CanFocus = true;
			this.ePortaLocal.Name = "ePortaLocal";
			this.ePortaLocal.IsEditable = true;
			this.ePortaLocal.InvisibleChar = '•';
			this.fixed3.Add(this.ePortaLocal);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.ePortaLocal]));
			w2.X = 165;
			w2.Y = 97;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("IP local:");
			this.fixed3.Add(this.label1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label1]));
			w3.X = 105;
			w3.Y = 66;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Porta local:");
			this.fixed3.Add(this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label2]));
			w4.X = 79;
			w4.Y = 104;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.WidthRequest = 80;
			this.btnCancelar.HeightRequest = 40;
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed3.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnCancelar]));
			w5.X = 55;
			w5.Y = 150;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnCriar = new global::Gtk.Button();
			this.btnCriar.WidthRequest = 80;
			this.btnCriar.HeightRequest = 40;
			this.btnCriar.CanFocus = true;
			this.btnCriar.Name = "btnCriar";
			this.btnCriar.UseUnderline = true;
			this.btnCriar.Label = global::Mono.Unix.Catalog.GetString("Criar");
			this.fixed3.Add(this.btnCriar);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnCriar]));
			w6.X = 248;
			w6.Y = 150;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Apelido:");
			this.fixed3.Add(this.label3);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label3]));
			w7.X = 102;
			w7.Y = 30;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.eApelido = new global::Gtk.Entry();
			this.eApelido.CanFocus = true;
			this.eApelido.Name = "eApelido";
			this.eApelido.IsEditable = true;
			this.eApelido.InvisibleChar = '•';
			this.fixed3.Add(this.eApelido);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.eApelido]));
			w8.X = 165;
			w8.Y = 24;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 381;
			this.DefaultHeight = 213;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.btnCancelar.Clicked += new global::System.EventHandler(this.OnBtnCancelarClicked);
			this.btnCriar.Clicked += new global::System.EventHandler(this.OnBtnCriarClicked);
		}
	}
}
