
// This file has been generated by the GUI designer. Do not modify.
namespace Bizingo
{
	public partial class ResetRequest
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label lTexto;

		private global::Gtk.Button bRecusar;

		private global::Gtk.Button bAceitar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Bizingo.ResetRequest
			this.WidthRequest = 270;
			this.HeightRequest = 270;
			this.Name = "Bizingo.ResetRequest";
			this.Title = global::Mono.Unix.Catalog.GetString("ResetRequest");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Bizingo.ResetRequest.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lTexto = new global::Gtk.Label();
			this.lTexto.Name = "lTexto";
			this.fixed2.Add(this.lTexto);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lTexto]));
			w1.X = 181;
			w1.Y = 68;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.bRecusar = new global::Gtk.Button();
			this.bRecusar.WidthRequest = 100;
			this.bRecusar.HeightRequest = 33;
			this.bRecusar.CanFocus = true;
			this.bRecusar.Name = "bRecusar";
			this.bRecusar.UseUnderline = true;
			this.bRecusar.Label = global::Mono.Unix.Catalog.GetString("Recusar");
			this.fixed2.Add(this.bRecusar);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.bRecusar]));
			w2.X = 75;
			w2.Y = 143;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.bAceitar = new global::Gtk.Button();
			this.bAceitar.WidthRequest = 100;
			this.bAceitar.HeightRequest = 33;
			this.bAceitar.CanFocus = true;
			this.bAceitar.Name = "bAceitar";
			this.bAceitar.UseUnderline = true;
			this.bAceitar.Label = global::Mono.Unix.Catalog.GetString("Aceitar");
			this.fixed2.Add(this.bAceitar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.bAceitar]));
			w3.X = 238;
			w3.Y = 143;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.bRecusar.Clicked += new global::System.EventHandler(this.OnBRecusarClicked);
			this.bAceitar.Clicked += new global::System.EventHandler(this.OnBAceitarClicked);
		}
	}
}
