
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 450;
		this.HeightRequest = 360;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 96;
		this.button6.HeightRequest = 43;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Criar Jogo");
		this.fixed2.Add(this.button6);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button6]));
		w1.X = 180;
		w1.Y = 136;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button7 = new global::Gtk.Button();
		this.button7.WidthRequest = 96;
		this.button7.HeightRequest = 43;
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Conectar");
		this.fixed2.Add(this.button7);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button7]));
		w2.X = 180;
		w2.Y = 190;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 450;
		this.DefaultHeight = 360;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button6.Clicked += new global::System.EventHandler(this.OnCriarJogo);
		this.button7.Clicked += new global::System.EventHandler(this.OnConectar);
	}
}
