
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.Action CloseAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.TextView logTextView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_File");
		w1.Add(this.FileAction, "<Alt>f");
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("_Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Open");
		w1.Add(this.OpenAction, "<Primary>o");
		this.CloseAction = new global::Gtk.Action("CloseAction", global::Mono.Unix.Catalog.GetString("C_lose"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString("C_lose");
		w1.Add(this.CloseAction, "<Primary>l");
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("E_xit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("E_xit");
		w1.Add(this.ExitAction, "<Primary>x");
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_Help");
		w1.Add(this.HelpAction, "<Primary>h");
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("_About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("_About");
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Messyo\'s log viewer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'/><menu name='OpenAction' action='OpenAction'/><menu name='CloseAction' action='CloseAction'/><menu name='ExitAction' action='ExitAction'/><menu name='HelpAction' action='HelpAction'/><menu name='AboutAction' action='AboutAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		this.logTextView = new global::Gtk.TextView();
		this.logTextView.CanFocus = true;
		this.logTextView.Name = "logTextView";
		this.logTextView.Editable = false;
		this.logTextView.CursorVisible = false;
		this.scrolledwindow1.Add(this.logTextView);
		this.vbox1.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
		w4.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 589;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler(this.OnOpen);
		this.CloseAction.Activated += new global::System.EventHandler(this.OnClose);
		this.ExitAction.Activated += new global::System.EventHandler(this.OnExit);
		this.HelpAction.Activated += new global::System.EventHandler(this.OnHelp);
		this.AboutAction.Activated += new global::System.EventHandler(this.OnAbout);
	}
}
