
// This file has been generated by the GUI designer. Do not modify.
namespace Bazinga
{
	public partial class teste
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Bazinga.teste
			this.Name = "Bazinga.teste";
			this.Title = global::Mono.Unix.Catalog.GetString("teste");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
