
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.DrawingArea drawingArea1;

	private global::Gtk.Label TimeStamp;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.drawingArea1 = new global::Gtk.DrawingArea();
		this.drawingArea1.WidthRequest = 200;
		this.drawingArea1.HeightRequest = 200;
		this.drawingArea1.Name = "drawingArea1";
		this.fixed1.Add(this.drawingArea1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.drawingArea1]));
		w1.X = 94;
		w1.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TimeStamp = new global::Gtk.Label();
		this.TimeStamp.Name = "TimeStamp";
		this.TimeStamp.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
		this.fixed1.Add(this.TimeStamp);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.TimeStamp]));
		w2.X = 167;
		w2.Y = 259;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
